{% set name = "tmmc-lnpy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tmmc_lnpy-{{ version }}.tar.gz
  sha256: aca7eaffcd9c77f36db5b440dec2159f8b80cfd38ef4dd01f0117a42351fa68a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<=3.12
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.8,<=3.12
    - bottleneck
    - importlib-resources
    - joblib
    - lazy_loader
    - module-utilities >=0.9.0
    - numpy
    - scikit-image >=0.21
    - scipy
    - tqdm
    - typing-extensions
    - xarray

test:
  imports:
    - lnpy
    - lnPi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/usnistgov/tmmc-lnpy
  summary: Analysis of lnPi results from TMMC simulation
  description: |
    A package to analyze data from Transition Matrix Monte Carlo (tmmc)
    simulation. The main output from TMMC simulations, "lnPi", provides a
    means to calculate a host of thermodynamic properties. Moreover, if "lnPi"
    is calculated at a specific chemical potential, it can be reweighted to provide
    thermodynamic information at a different chemical potential.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
