{% set name = "tmmc-lnpy" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tmmc_lnpy-{{ version }}.tar.gz
  sha256: f03459bb21fdf5fb65e07f98284d1cdbef6d95317fcc830f2552027557361db5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.11.0,<0.12.0
    - pip
  run:
    - python >={{ python_min }}
    - bottleneck
    - importlib-resources
    - joblib
    - lazy_loader
    - module-utilities >=0.9.0
    - numba
    - numpy
    - pandas >=2.3.0
    - pooch
    - scikit-image >=0.21
    - scipy
    - tqdm
    - typing-extensions
    - xarray

test:
  imports:
    - lnpy
    - lnPi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/tmmc-lnpy
  summary: Analysis of lnPi results from TMMC simulation
  description: |
    A package to analyze data from Transition Matrix Monte Carlo (tmmc)
    simulation. The main output from TMMC simulations, "lnPi", provides a
    means to calculate a host of thermodynamic properties. Moreover, if "lnPi"
    is calculated at a specific chemical potential, it can be reweighted to provide
    thermodynamic information at a different chemical potential.
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
